### ISSUE TITLE
Support for SD 1.5

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [failfa-st/LoRAdo#2]
**Feature Request:**
It would be amazing if LoRAdo could support SD 1.5.

I'm not sure what changes would need to be made and which features wouldn't be supported, but it would let more people use the tool and make their training easier! A  healthier life for everyone please!

**Comment by pixelass** [comment]
Thank you for the request. We will look into it.

**Comment by pixelass** [comment]
currently disabled, but we're working on it


![image](https://github.com/failfa-st/LoRAdo/assets/1148334/7464c1a6-65bf-4e2a-b8b2-ca4e4e1db315)

**Comment by MNeMoNiCuZ** [comment]
Nice! That looks like a good solution.
If the "Checkpoint (SDXL)" text also updates based on the toggle, that would be luxurious.

**Comment by pixelass** [comment]
THe `(SDXL)` in the label will be removed when the feature is enabled. It is just to make sure that it is clear, that currently ony SDXL is supported

**Comment by pixelass** [comment]
Looking good (SDXL cropping).

![image](https://github.com/failfa-st/LoRAdo/assets/1148334/32870043-7ee2-44a6-b1f9-a1943904c3ce)

**Comment by pixelass** [comment]
implemented in v0.1.0-alpha.5

**Comment by MNeMoNiCuZ** [comment]
Nice! I'll take it out for a test-drive tomorrow! I may ping for some assistance if I can't figure things out :D
