### ISSUE TITLE
Define the Node versions that are actually working in README

### ISSUE THREAD

**Issue by TimPietrusky** [failfa-st/LoRAdo#6]
**Is your feature request related to a problem? Please describe.** 
It's annoying that during installation with `npm install` some node versions are not working, see https://github.com/failfa-st/LoRAdo/issues/1. It would be nice if we would define the working Node-Versions in the README, so that people can check if they have a supported version and are not running into problems and have to ask us. 

**Describe the solution you'd like** 
* Test  the supported versions of Node
* Write down the supported versions in the README, so that everyone can see them instantly 

**Describe alternatives you've considered**
* Go on Discord to ask a question
* Search on GitHub issues to find the closed issue, that is actually not resolved, as I still don't know which versions are working

**Comment by pixelass** [comment]
done and done including build confirmation
![image](https://github.com/failfa-st/LoRAdo/assets/1148334/040d8373-5f9a-4163-a0b1-d757a4e86d46)
